{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-07-03T14:33:41.958Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-07-03T14:33:41.961Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-07-03T14:33:41.962Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-07-03T14:49:26.349Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-07-03T14:49:26.353Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"warn","timestamp":"2018-07-03T14:49:26.353Z"}
